### ISSUE TITLE
Integration test and example of GSS-TSIG for DNS update

### ISSUE THREAD

**Issue by jcmturner** [jcmturner/gokrb5#241]
Write an integration test for GSS-TSIG performing a DNS update.

Add to the examples directory code that does GSS-TSIG DNS update.

**Comment by jcmturner** [comment]
@bodgit I was thinking of implementing an integration test of the DNS update using GSS-TSIG. I have a bind DNS container as part of the travis tests. I could set that up to do a DNS update using GSS-TSIG. Do you have some code you are using to do this that could form the basis of this integration test?

**Comment by bodgit** [comment]
The library that does all of the heavy lifting is here: https://github.com/bodgit/tsig

A working example is documented here: https://github.com/bodgit/tsig/blob/master/gss/gss.go

You could replace the `NegotiateContext()` call with `NegotiateContextWithCredentials()` or `NegotiateContextWithKeytab()` as appropriate if you wanted to use a user other than the current one with either a known password or a keytab file.

However, it relies on an as-yet unmerged PR to the github.com/miekg/dns library so that is supports TSIG methods other than the standard HMAC ones. I have this as a fork here: https://github.com/bodgit/dns/tree/gss-tsig
