### ISSUE TITLE
Why does the SSO not work and the authorization window appears?

### ISSUE THREAD

**Issue by nurzhannogerbek** [jcmturner/gokrb5#389]
First of all, thank you very much for this wonderful project! =)

Not so long ago I noticed that the project was updated to version: `github.com/jcmturner/gokrb5/v8`. I'm currently using the `gopkg.in/jcmturner/gokrb5.v7@7.5.0` version of the project. I'm thinking of updating the project to the last version. Also, I use [httpServer.go](https://github.com/jcmturner/gokrb5/blob/master/examples/httpServer.go) example in my own  application. Are you thinking of updating the examples code for version 8?

I was distracted. I actually have a problem right now that I can't solve. When I make a request to my own REST API service via the browser, I see the following window in the browser:
![57](https://user-images.githubusercontent.com/8999232/80962645-39a5dd80-8e2f-11ea-949b-99e470f53b58.JPG)

Why does this window appear? I entered my personal data in this window and see the following error:

> 2020/05/04 17:16:02 /go/pkg/mod/gopkg.in/jcmturner/gokrb5.v7@v7.5.0/spnego/spnego.go:95: 192.168.238.182:54408 - SPNEGO error in unmarshaling SPNEGO token: not a valid SPNEGO token: asn1: structure error: explicitly tagged member didn't match

This problem appears in the Chrome browser. However, Edge does not have it, and I get a response to my request in the browser without this window. Where can I find the reason for this strange behavior with the window? Please let me know if you need more information.

**main.go**:
```
package main

import (
	"my_service/controllers"
	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
	"gopkg.in/jcmturner/gokrb5.v7/keytab"
	"gopkg.in/jcmturner/gokrb5.v7/service"
	"gopkg.in/jcmturner/gokrb5.v7/spnego"
	"net/http"
)


func main() {
	// Create logger.
	logger := log.New(os.Stderr, "GOKRB5 Service: ", log.Ldate|log.Ltime|log.Lshortfile)

	// Load the service's keytab.
	serviceKeytab, err := keytab.Load("./dependencies/secret.keytab"); if err != nil {
		panic(err)
	}


	// Router instance.
	router := mux.NewRouter()

	// CORS settings.
	headers := handlers.AllowedHeaders([]string{"X-Requested-With", "Content-Type", "Authorization"})
	methods := handlers.AllowedMethods([]string{"GET", "POST", "PATCH", "PUT", "DELETE", "OPTIONS"})
	origins := handlers.AllowedOrigins([]string{"*"})
	credentials := handlers.AllowCredentials()

	// Endpoint address.
	router.Handle("/api/hrc/employee",
		spnego.SPNEGOKRB5Authenticate(
			http.HandlerFunc(controllers.GetInformation),
			serviceKeytab,
			service.Logger(logger),
			service.KeytabPrincipal("SERVICE_NAME"))

	// Start to listen and serve the application.
	utils.Logger().Fatal(http.ListenAndServe(":8000", handlers.CORS(headers, methods, origins, credentials)(router)))
}
```

**Comment by jcmturner** [comment]
Hi @nurzhannogerbek 

With regards to updating the example code, this should be up to date for version 8 and found at https://github.com/jcmturner/gokrb5/tree/master/v8/examplesLet me know if you think there is something missing.

With regards to the issue you are seeing this is probably due to the configuration of the Chrome browser. You have to configure the browser to trust certain domains to automatically send authorisation tokens to sites in these domains. If this is not configured then the browser will fall back to trying to ask the user for credentials. See the link below for how to configure various browsers for SPNEGO SSO...https://docs.cloudera.com/documentation/enterprise/latest/topics/cdh_sg_browser_access_kerberos_protected_url.html
