### ISSUE TITLE
crypto/common/common.go:157:3: constant 4294967296 overflows int

### ISSUE THREAD

**Issue by DamjanJovanovic** [jcmturner/gokrb5#74]
$ dep status
PROJECT                                         CONSTRAINT     VERSION        REVISION  LATEST   PKGS USED
gopkg.in/jcmturner/gokrb5.v2                    v2.1.1         v2.1.1         fbb9b86   fbb9b86  30  

$ go build
vendor/gopkg.in/jcmturner/gokrb5.v2/crypto/common/common.go:157:3: constant 4294967296 overflows int
vendor/gopkg.in/jcmturner/gokrb5.v2/crypto/common/common.go:161:3: constant 4294967296 overflows int
vendor/gopkg.in/jcmturner/gokrb5.v2/crypto/common/common.go:167:3: constant 4294967296 overflows int

**Comment by DamjanJovanovic** [comment]
This was on a 32 bit system by the way. You need to return uint instead and to subtract 1 from 4294967296, or return (u)int64 and do more extensive fixes elsewhere.

There is at least one other compile time error on 32 bit.

**Comment by jcmturner** [comment]
There is a limitation due to the golang.org/x/crypto/pbkdf2 package and its Key() function taking an int as input.

I have submitted a patch to this library to use the big.Int as input (https://go-review.googlesource.com/c/crypto/+/85535)

In the meantime I have worked around this by forking the library.

It would be helpful if you can test by building using the source on branch issue-74
You will also need to: ```go get github.com/jcmturner/gofork```

If you can confirm this resolves things I can merge to master. Thanks.

This is likely to lead to incrementing the major version of gokrb5 to gokrb5.v3 as it has changed some of the public methods.
