### ISSUE TITLE
Ability to create configuration from default locations of krb5.conf

### ISSUE THREAD

**Issue by F21** [jcmturner/gokrb5#8]
This might be useful for the `config` package to augment `Load`.

For example, `config, err := config.LoadFromDefaultLocations()`, which would attempt to load configuration from the following locations:

| Windows    | c:\winnt\krb5.ini                                    |
|------------|------------------------------------------------------|
| Windows    | c:\windows\krb5.ini                                  |
| Linux      | /etc/krb5.conf                                       |
| Other Unix | /etc/krb5/krb5.conf                                  |
| z/OS       | /etc/krb5/krb5.conf                                  |
| IBM i      | /QIBM/UserData/OS400/NetworkAuthentication/krb5.conf |
| Solaris    | /etc/krb5/krb5.conf                                  |

The file paths are from these 2 references:
- https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/tutorials/KerberosReq.html
- https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.nd.doc/ae/rsec_SPNEGO_config_krb5.html

**Comment by jcmturner** [comment]
There is a NewConfigFromReader(r io.Reader) method which you could use to achieve this. If you create a type that implements the io.Reader interface and has the logic to figure out and use the default location in the implemented Read method you could then just pass it into this method to return the config object. 

Personally I think that your application should own its own configuration rather than rely on an OS level configuration. You end up tightly coupling the application to the OS level configuration and this can lead to confusion in where configuration is and what it authoritative over that configuration. I also worry about an implicit configuration like this. Config files being found like this leads to issues in production where it can be unclear how something gets configured. I think it is better to be explicit about the application's configuration. For these reasons I won't be implementing the method you suggested but if you still wish to achieve it you still can with the approach I outlined above.

**Comment by F21** [comment]
@jcmturner Thanks, that makes a lot of sense!
