### ISSUE TITLE
Cannot go get

### ISSUE THREAD

**Issue by airnandez** [jcmturner/gokrb5#84]
Installation instructions of this package do not work for me:

```
$ go get gopkg.in/jcmturner/gokrb5.v3
package gopkg.in/jcmturner/gokrb5.v3: no Go files in $GOPATH/src/gopkg.in/jcmturner/gokrb5.v3
```

Tested in two environments:

```
# CentOS 7
$ go version
go version go1.9.2 linux/amd64

# macOS 10.11
$ go version
go version go1.9.2 darwin/amd64
```

Am I missing something?

**Comment by jcmturner** [comment]
I think this error is due to the fact there are no go files directly in the gokrb5.v3 directory. However if you check there should be the other directories and go files downloaded. Have a look in $GOPATH/src/gopkg.in/jcmturner/gokrb5.v3/

I may add a go file to the root directory of gokrb5 just to eliminate this confusing error from go get.

**Comment by jcmturner** [comment]
Added a go file to eliminate this error. This will go into the next release version.
